# GitHub Pages configuration for TRX Cap
title: TRX Cap Bundle
description: Always up-to-date JavaScript bundle for TRX Cap
url: https://23cubed.github.io
baseurl: /trx-cap

# Serve all files as-is (no Jekyll processing)
plugins: []
markdown: kramdown
highlighter: rouge

# Include JavaScript files
include:
  - latest.js 